name: Honiball
favicon: null
layout_spectrum: 0.3339564341586083
typography_spectrum: 0.3220866753254086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.23971183691173792
  lightness: 0.8853404652327299
  saturation: 0.5694513313937932
  rhythmicContrast: 0.29633712279610336
purpose: []
